[auth]
redirect_uri = "https://darkknightrises.streamlit.app/oauth2callback"
cookie_secret = "xxxfgh567ftgrjabjdsa899bjsaghdgjhhf"

[auth.auth0]
domain = "dev-hbp7wroop2d5uim5.eu.auth0.com"
client_id = "mCyvQa0ZmUTWgDEyjdutkofkIcMs4Ovr"
client_secret = "HN2XG1eDA9Km1nhihgMaBeNtMGq_mETYmXLyRn54bKQ-hEBByb4um7bd8aY2l4Db"
server_metadata_url = "https://dev-hbp7wroop2d5uim5.eu.auth0.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }
