[auth]
redirect_uri = "https://darkknightrises.streamlit.app//login"
cookie_secret = "xxxfgh567ftgrjabjdsa899bjsaghd"
client_id = "ZFvqLvocgZgdx1r2hAMB0O3enzNoAVyM"
client_secret = "8BjcoXT7wuzM58WjMFyX-bYjM98HZ5oQ3ltk0LhCEkd8dzYb3a_bDKEsZcss4cDy"
server_metadata_url = (
    "https://dev-hbp7wroop2d5uim5.eu.auth0.com/.well-known/openid-configuration"
)
